version: '3.2'
services: 
    db:
        image: mongo
        restart: always
        command: mongod
        ports:
            - 4000:27017
    api:
        depends_on:
            - db
        image: mystichan/td-evry-mysti-api
        ports: 
            - 3000:3000
            - 3010:3010
        
    front:
        depends_on:
            - api
        image: mystichan/td-evry-mysti-front
        ports: 
            - 4200:4200
